path: "tensorflow.keras.optimizers.experimental.EMAOption"
tf_class {
  is_instance: "<class \'keras.optimizer_experimental.optimizer_lib.EMAOption\'>"
  is_instance: "<type \'object\'>"
  member_method {
    name: "__init__"
    argspec: "args=[\'self\', \'use_ema\', \'ema_momentum\', \'ema_overwrite_frequency\'], varargs=None, keywords=None, defaults=[\'False\', \'0.99\', \'100\'], "
  }
  member_method {
    name: "get_config"
    argspec: "args=[\'self\'], varargs=None, keywords=None, defaults=None"
  }
}
